name: C Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install GCC
      run: sudo apt-get install gcc
    - name: Compile
      run: gcc -o mioprogramma mioprogramma.c
    - name: Run
      run: ./mioprogramma
